### ISSUE TITLE
Grunt fails because of missing 'use strict'

### ISSUE THREAD

**Issue by i8ramin** [brendanoffer/WeWork-weather-widget#1]
Just an FYI .. going through the app now.

```
app/scripts/factories/location-factory.js
  line 3   col 3    Missing "use strict" statement.
```

**Comment by brendanoffer** [comment]
Hey Ramin,

Sorry about that.  Will fix tonight, as I am currently at work.  If you have any other concerns / questions please let me know.  

grunt might throw some warnings as well, 'grunt --force' should complete the build.
